# Default configuration for offline jekyll site generation

:absolute_base: "https://address.of.site.com/" # The full URL of the site as it might appear in any absolute links on the website. (these will be converted to relative links)
:relative_base: "/blog" # Optional - use this if the original site is located in a subdirectory
:source_dir: "~/Downloads/spiffy_website/_site/" # This should point to the _site folder of the generated Jekyll website
:out_dir: "~/my_website_offline/" # The desired output directory where you would like to generate the offline version of the site
# :custom_filter: "fn:|fnref:" # Optional: specify a custom string to filter -- URLS containing this string will not be rewritten

# boilerplate variables
:site_title: "My Website Title"
:site_url: "https://address.of.site.com/" # URL of the original site
:site_logo: "" # Image to use for site logo on intro page
