# Default configuration for offline jekyll site generation

:source: "~/workspace/root/_site" # This should point to the _site folder of the generated Jekyll website
:target: "~/Downloads" # The desired output directory where you would like to generate the offline version of the site
:site_url: "http://localhost:4000" # URL of the original site (http://localhost:4000/)
